---
title: "Mercer County - Dashboard"
output: html_document
---


```{r setup, include=FALSE}
library(readxl)
library(knitr)
library(ggplot2)
library(gapminder)
library(dplyr)

Blair <- read_excel("Mercer_County_Report_V10.xlsx", sheet = 2)
Blair
```

```{css, echo=FALSE}
.twoC {width: 100%}
.clearer {clear: both}
.twoC .table {max-width: 50%; float: right}
.twoC img {max-width: 50%; float: left}
```


```{r echo=FALSE}
Blair1 <- Blair[c(1:7),]

Blair1$Percent <- round(as.numeric(Blair1$`%`)*100, 0)
Blair1$Color <- ifelse(Blair1$Percent < 50, "red",
                       ifelse(Blair1$Percent >= 50 & Blair1$Percent < 75, "orange",
                              ifelse(Blair1$Percent >= 75 & Blair1$Percent< 100, "yellow",
                                     ifelse(Blair1$Percent == 100, "green", NA))))

Blair1 <- arrange(Blair1, desc(Blair1$ORGTYPE))

Blair2 <- Blair[c(13:14),]

Blair2$Percent <- round(as.numeric(Blair2$`%`)*100, 0)
Blair2$Color <- ifelse(Blair2$Percent < 50, "red",
                       ifelse(Blair2$Percent >= 50 & Blair2$Percent < 75, "orange",
                              ifelse(Blair2$Percent >= 75 & Blair2$Percent< 100, "yellow",
                                     ifelse(Blair2$Percent == 100, "green", NA))))

Blair2 <- arrange(Blair2, desc(Blair2$ORGTYPE))

Blair3 <- Blair[c(9,16,17),]

Blair3$Percent <- round(as.numeric(Blair3$`%`)*100, 0)
Blair3$Color <- ifelse(Blair3$Percent < 50, "red",
                       ifelse(Blair3$Percent >= 50 & Blair3$Percent < 75, "orange",
                              ifelse(Blair3$Percent >= 75 & Blair3$Percent< 100, "yellow",
                                     ifelse(Blair3$Percent == 100, "green", NA))))

Blair3$ORGTYPE <- c("Core Total", "Peripheral Total", "Overall Total")

```


```{r echo=FALSE}
ggplot(Blair3, aes(x=Percent, y=ORGTYPE, col=Color, fill=Color)) + 
  geom_bar(stat="identity") + 
  scale_fill_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  scale_color_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  theme(legend.position = "none", 
        panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y= element_blank()) +
  geom_text(aes(x=Percent, label=Percent),hjust=1, color="black", size=4) +
  xlim(0,100) +
  geom_vline(xintercept=50, color ='#D11141', linetype = "dashed", size =.75) +
  geom_vline(xintercept=75, color ="#ffc425", linetype = "dashed", size =.75) +
  geom_vline(xintercept=100, color ='#00b159', linetype= "dashed", size =.75) +
  scale_y_discrete(limits=c("Overall Total", "Peripheral Total", "Core Total"))
```

```{r echo=FALSE}
kable(Blair3[,c(1:3,5)])
```


## Core
<div class="twoC">

```{r echo=FALSE}
ggplot(Blair1, aes(x=Percent, y=ORGTYPE, col=Color, fill=Color)) + 
  geom_bar(stat="identity") + 
  scale_fill_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  scale_color_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  theme(legend.position = "none", 
        panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y= element_blank()) +
  geom_text(aes(x=Percent, label=Percent),hjust=1, color="black", size=4) +
  xlim(0,100) +
  geom_vline(xintercept=50, color ='#D11141', linetype = "dashed", size =.75) +
  geom_vline(xintercept=75, color ="#ffc425", linetype = "dashed", size =.75) +
  geom_vline(xintercept=100, color ='#00b159', linetype= "dashed", size =.75)
```

```{r echo=FALSE}
kable(Blair1[,c(1:3,5)])

```
</div>
<div class="clearer"></div>

## Peripheral

<div class="twoC">
```{r echo=FALSE}
ggplot(Blair2, aes(x=Percent, y=ORGTYPE, col=Color, fill=Color)) + 
  geom_bar(stat="identity") + 
  scale_fill_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  scale_color_manual(values=c("green"="#00b159","orange"='#f37735',"red"="#D11141","yellow"="#ffc425")) + 
  theme(legend.position = "none", 
        panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.y= element_blank()) +
  geom_text(aes(x=Percent, label=Percent),hjust=1, color="black", size=4) +
  xlim(0,100) +
  geom_vline(xintercept=50, color ='#D11141', linetype = "dashed", size =.75) +
  geom_vline(xintercept=75, color ="#ffc425", linetype = "dashed", size =.75) +
  geom_vline(xintercept=100, color ='#00b159', linetype= "dashed", size =.75)
```

```{r echo=FALSE}
kable(Blair2[,c(1:3,5)])
```
</div>
<div class="clearer"></div>